import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

// NOTE: auto-generated by `payload migrate:create`, then hand-trimmed. The generator diffs
// against the migrations/*.json snapshot rather than the live DB, and this dev DB had drifted
// from that snapshot (years of `push`-mode dev schema syncing) — so the raw output bundled in
// a large amount of unrelated `insights_blocks_*` CREATE TABLE statements for tables that
// already exist live, which would fail with "relation already exists". Everything below is only
// what Article.ts's `content` field (richText -> blocks: [StructuredTextBlock, SupportCtaSection])
// actually needs.

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."enum_articles_blocks_structured_text_block_bg" AS ENUM('default', 'lighter', 'primary-light', 'primary', 'dark');
  CREATE TYPE "public"."enum_articles_blocks_support_cta_section_bg" AS ENUM('default', 'lighter', 'primary-light', 'primary', 'dark');
  CREATE TABLE "articles_blocks_structured_text_block" (
  	"_order" integer NOT NULL,
  	"_parent_id" uuid NOT NULL,
  	"_path" text NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"bg" "enum_articles_blocks_structured_text_block_bg",
  	"content" jsonb NOT NULL,
  	"block_name" varchar
  );

  CREATE TABLE "articles_blocks_internal_link" (
  	"_order" integer NOT NULL,
  	"_parent_id" uuid NOT NULL,
  	"_path" text NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"label" varchar NOT NULL,
  	"block_name" varchar
  );

  CREATE TABLE "articles_blocks_external_link" (
  	"_order" integer NOT NULL,
  	"_parent_id" uuid NOT NULL,
  	"_path" text NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"label" varchar NOT NULL,
  	"url" varchar NOT NULL,
  	"description" varchar,
  	"block_name" varchar
  );

  CREATE TABLE "articles_blocks_support_cta_section" (
  	"_order" integer NOT NULL,
  	"_parent_id" uuid NOT NULL,
  	"_path" text NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"title" varchar NOT NULL,
  	"paragraph" varchar NOT NULL,
  	"image_id" uuid NOT NULL,
  	"bg" "enum_articles_blocks_support_cta_section_bg",
  	"block_name" varchar
  );

  ALTER TABLE "articles_rels" ADD COLUMN "pages_id" uuid;
  ALTER TABLE "articles_rels" ADD COLUMN "articles_id" uuid;
  ALTER TABLE "articles_rels" ADD COLUMN "insights_id" uuid;
  ALTER TABLE "articles_rels" ADD COLUMN "webinar_items_id" uuid;
  ALTER TABLE "articles_rels" ADD COLUMN "story_items_id" uuid;
  ALTER TABLE "articles_rels" ADD COLUMN "catalogues_id" uuid;
  ALTER TABLE "articles_blocks_structured_text_block" ADD CONSTRAINT "articles_blocks_structured_text_block_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."articles"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "articles_blocks_internal_link" ADD CONSTRAINT "articles_blocks_internal_link_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."articles"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "articles_blocks_external_link" ADD CONSTRAINT "articles_blocks_external_link_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."articles"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "articles_blocks_support_cta_section" ADD CONSTRAINT "articles_blocks_support_cta_section_image_id_media_id_fk" FOREIGN KEY ("image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "articles_blocks_support_cta_section" ADD CONSTRAINT "articles_blocks_support_cta_section_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."articles"("id") ON DELETE cascade ON UPDATE no action;
  CREATE INDEX "articles_blocks_structured_text_block_order_idx" ON "articles_blocks_structured_text_block" USING btree ("_order");
  CREATE INDEX "articles_blocks_structured_text_block_parent_id_idx" ON "articles_blocks_structured_text_block" USING btree ("_parent_id");
  CREATE INDEX "articles_blocks_structured_text_block_path_idx" ON "articles_blocks_structured_text_block" USING btree ("_path");
  CREATE INDEX "articles_blocks_structured_text_block_locale_idx" ON "articles_blocks_structured_text_block" USING btree ("_locale");
  CREATE INDEX "articles_blocks_internal_link_order_idx" ON "articles_blocks_internal_link" USING btree ("_order");
  CREATE INDEX "articles_blocks_internal_link_parent_id_idx" ON "articles_blocks_internal_link" USING btree ("_parent_id");
  CREATE INDEX "articles_blocks_internal_link_path_idx" ON "articles_blocks_internal_link" USING btree ("_path");
  CREATE INDEX "articles_blocks_internal_link_locale_idx" ON "articles_blocks_internal_link" USING btree ("_locale");
  CREATE INDEX "articles_blocks_external_link_order_idx" ON "articles_blocks_external_link" USING btree ("_order");
  CREATE INDEX "articles_blocks_external_link_parent_id_idx" ON "articles_blocks_external_link" USING btree ("_parent_id");
  CREATE INDEX "articles_blocks_external_link_path_idx" ON "articles_blocks_external_link" USING btree ("_path");
  CREATE INDEX "articles_blocks_external_link_locale_idx" ON "articles_blocks_external_link" USING btree ("_locale");
  CREATE INDEX "articles_blocks_support_cta_section_order_idx" ON "articles_blocks_support_cta_section" USING btree ("_order");
  CREATE INDEX "articles_blocks_support_cta_section_parent_id_idx" ON "articles_blocks_support_cta_section" USING btree ("_parent_id");
  CREATE INDEX "articles_blocks_support_cta_section_path_idx" ON "articles_blocks_support_cta_section" USING btree ("_path");
  CREATE INDEX "articles_blocks_support_cta_section_locale_idx" ON "articles_blocks_support_cta_section" USING btree ("_locale");
  CREATE INDEX "articles_blocks_support_cta_section_image_idx" ON "articles_blocks_support_cta_section" USING btree ("image_id");
  ALTER TABLE "articles_rels" ADD CONSTRAINT "articles_rels_pages_fk" FOREIGN KEY ("pages_id") REFERENCES "public"."pages"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "articles_rels" ADD CONSTRAINT "articles_rels_articles_fk" FOREIGN KEY ("articles_id") REFERENCES "public"."articles"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "articles_rels" ADD CONSTRAINT "articles_rels_insights_fk" FOREIGN KEY ("insights_id") REFERENCES "public"."insights"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "articles_rels" ADD CONSTRAINT "articles_rels_webinar_items_fk" FOREIGN KEY ("webinar_items_id") REFERENCES "public"."webinar_items"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "articles_rels" ADD CONSTRAINT "articles_rels_story_items_fk" FOREIGN KEY ("story_items_id") REFERENCES "public"."story_items"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "articles_rels" ADD CONSTRAINT "articles_rels_catalogues_fk" FOREIGN KEY ("catalogues_id") REFERENCES "public"."catalogues"("id") ON DELETE cascade ON UPDATE no action;
  CREATE INDEX "articles_rels_pages_id_idx" ON "articles_rels" USING btree ("pages_id","locale");
  CREATE INDEX "articles_rels_articles_id_idx" ON "articles_rels" USING btree ("articles_id","locale");
  CREATE INDEX "articles_rels_insights_id_idx" ON "articles_rels" USING btree ("insights_id","locale");
  CREATE INDEX "articles_rels_webinar_items_id_idx" ON "articles_rels" USING btree ("webinar_items_id","locale");
  CREATE INDEX "articles_rels_story_items_id_idx" ON "articles_rels" USING btree ("story_items_id","locale");
  CREATE INDEX "articles_rels_catalogues_id_idx" ON "articles_rels" USING btree ("catalogues_id","locale");
  ALTER TABLE "articles_locales" DROP COLUMN "content";`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   DROP TABLE "articles_blocks_structured_text_block" CASCADE;
  DROP TABLE "articles_blocks_internal_link" CASCADE;
  DROP TABLE "articles_blocks_external_link" CASCADE;
  DROP TABLE "articles_blocks_support_cta_section" CASCADE;
  ALTER TABLE "articles_rels" DROP CONSTRAINT "articles_rels_pages_fk";
  ALTER TABLE "articles_rels" DROP CONSTRAINT "articles_rels_articles_fk";
  ALTER TABLE "articles_rels" DROP CONSTRAINT "articles_rels_insights_fk";
  ALTER TABLE "articles_rels" DROP CONSTRAINT "articles_rels_webinar_items_fk";
  ALTER TABLE "articles_rels" DROP CONSTRAINT "articles_rels_story_items_fk";
  ALTER TABLE "articles_rels" DROP CONSTRAINT "articles_rels_catalogues_fk";
  DROP INDEX "articles_rels_pages_id_idx";
  DROP INDEX "articles_rels_articles_id_idx";
  DROP INDEX "articles_rels_insights_id_idx";
  DROP INDEX "articles_rels_webinar_items_id_idx";
  DROP INDEX "articles_rels_story_items_id_idx";
  DROP INDEX "articles_rels_catalogues_id_idx";
  ALTER TABLE "articles_locales" ADD COLUMN "content" jsonb;
  ALTER TABLE "articles_rels" DROP COLUMN "pages_id";
  ALTER TABLE "articles_rels" DROP COLUMN "articles_id";
  ALTER TABLE "articles_rels" DROP COLUMN "insights_id";
  ALTER TABLE "articles_rels" DROP COLUMN "webinar_items_id";
  ALTER TABLE "articles_rels" DROP COLUMN "story_items_id";
  ALTER TABLE "articles_rels" DROP COLUMN "catalogues_id";
  DROP TYPE "public"."enum_articles_blocks_structured_text_block_bg";
  DROP TYPE "public"."enum_articles_blocks_support_cta_section_bg";`)
}
